version: 0.2

phases:
  install:
    commands:
      - echo "Installing kubectl"
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.29.0/2023-11-14/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client
      - aws --version

  pre_build:
    commands:
      - echo "Who am I?"
      - aws sts get-caller-identity

      - echo "Updating kubeconfig"
      - aws eks update-kubeconfig --region ap-northeast-1 --name eksdemo1

      - echo "Kubeconfig content"
      - cat ~/.kube/config

      - echo "Testing cluster access"
      - kubectl cluster-info
      - kubectl get nodes

  build:
    commands:
      - kubectl apply -f kube-manifests/
