version: 0.2

phases:
  install:
    commands:
      - echo "Installing kubectl"
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.29.0/2023-11-14/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo "Updating kubeconfig"
      - aws eks update-kubeconfig --region ap-northeast-1 --name eksdemo1

      - echo "Listing files"
      - ls -R .

      - echo "Loading image variables"
      - source ./exported-vars.env
      - echo "IMAGE_URI=$IMAGE_URI"
      - echo "IMAGE_TAG=$IMAGE_TAG"

      - echo "Updating deployment YAML"
      - sed -i 's@CONTAINER_IMAGE@'"$IMAGE_URI:$IMAGE_TAG"'@' kube-manifests/01-DEVOPS-Nginx-Deployment.yml
      - cat kube-manifests/01-DEVOPS-Nginx-Deployment.yml

  build:
    commands:
      - echo "Deploying to EKS"
      - kubectl apply -f kube-manifests/

  post_build:
    commands:
      - echo "Pods:"
      - kubectl get pods -o wide
      - echo "Services:"
      - kubectl get svc -o wide
